[env:custom_build]
extends = env:esp32dev
build_flags = ${env:esp32dev.build_flags} ${common.debug_flags} -D LEDPIN=6 -D USERMOD_WORDCLOCK -D RGB_ROTARY_ENCODER -D USERMOD_PWM_OUTPUTS
lib_deps = 
  ${env:esp32dev.lib_deps}
  lennarthennigs/ESP Rotary@^1.5.0
